version: '3.8'

services:
  taskmanager-db:
    image: mysql:8.0
    container_name: taskmanager-db
    restart: always
    environment:
      MYSQL_DATABASE: taskdb
      MYSQL_USER: app_user
      MYSQL_PASSWORD: ${APPUSER_PASSWORD:-defaultpassword}
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  taskmanager-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taskmanager-api
    depends_on:
      - taskmanager-db
    environment:
      APPUSER_PASSWORD: ${APPUSER_PASSWORD:-defaultpassword}
    ports:
      - "8080:8080"

volumes:
  db_data:
