spring:
  liquibase:
    change-log: classpath:db/changelog/taskmanager.changelog.yaml
    enabled: false

  datasource:
    url: jdbc:mysql://localhost:3306/taskdb?allowPublicKeyRetrieval=true&useSSL=false
    username: app_user
    password: ${APPUSER_PASSWORD:defaultpassword}
    driver-class-name: com.mysql.cj.jdbc.Driver

management:
  endpoints:
    jmx:
      exposure:
        include: "health,info"
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect