openapi: 3.0.3
info:
  title: Task Manager API
  version: 1.0.0
paths: {}
components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        description:
          type: string
        status:
          type: string
          enum: [Pending, In_Progress, Completed]
        deadline:
          type: string
          format: date-time
      required:
        - title
        - description
